package com.example.vocab.presentation

import android.app.Application
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.viewModelScope
import com.example.vocab.data.DictionaryRepositoryImpl
import com.example.vocab.domain.entities.Word
import com.example.vocab.domain.use_cases.AddGeneralWordUseCase
import com.example.vocab.domain.use_cases.DeleteGeneralWordUseCase
import com.example.vocab.domain.use_cases.GetGeneralDictionaryUseCase
import com.example.vocab.domain.use_cases.GetUserDictionaryUseCase
import kotlinx.coroutines.launch

class MainViewModel(application: Application) : AndroidViewModel(application) {

    private val repository = DictionaryRepositoryImpl(application)
    private val getGeneralDictionaryUseCase = GetGeneralDictionaryUseCase(repository)
    private val getUserDictionaryUseCase = GetUserDictionaryUseCase(repository)
    private val addGeneralWordUseCase = AddGeneralWordUseCase(repository)
    private val deleteGeneralWordUseCase = DeleteGeneralWordUseCase(repository)

    val userDictionary = getUserDictionaryUseCase.getUserDictionary() // LiveData<List<Word>>

    suspend fun addGeneralWord(word: Word) {
        viewModelScope.launch {
            addGeneralWordUseCase.addGeneralWord(word)
        }
    }

//    fun getGeneralThematics(): List<String> {
//        MediatorLiveData<List<Word>>().apply {
//            addSource(getGeneralDictionaryUseCase.getGeneralDictionary()) {
//                val resultMap = mutableMapOf<String, MutableList<Word>>()
//                for (word in it) {
//                    if (resultMap.containsKey(word.thematics)) {
//                        resultMap[word.thematics]?.add(word)
//                    } else {
//                        resultMap[word.thematics] = mutableListOf(word)
//                    }
//                }
//                value = resultMap.keys.toList()
//            }
//        }
//    }

    // load word into GeneralDictionary
    init {
        viewModelScope.launch {
//            for (i in 1..44L) {
//                deleteGeneralWordUseCase.deleteGeneralWord(i)
//            }
//            with(addGeneralWordUseCase){
//                addGeneralWord(Word(0, "arise (arose, arisen)", "Возникать, появляться", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "awake (awakened/awoke, awakened/awoken)", "Будить, проснуться", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "backslide (backslid, backslidden/backslid)", "Отказываться от прежних убеждений", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "be (was were, been)", "Быть", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "bear (bore, born/borne)", "Родить", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "beat (beat, beaten/beat)", "Бить", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "become (became, become)", "Становиться, делаться", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "begin (began, begun)", "Начинать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "bend (bent, bent)", "Сгибать, гнуть", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "bet (bet/betted, bet/betted)", "Держать пари", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "bind (bound, bound)", "Связать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "bite (bit, bitten)", "Кусать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "bleed (bled, bled)", "Кровоточить", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "blow (blew, blown)", "Дуть", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "break (broke, broken)", "Ломать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "breed (bred, bred)", "Выращивать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "bring (brought, brought)", "Приносить", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "broadcast (broadcast/broadcasted, broadcast/broadcasted)", "Распространять, разбрасывать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "browbeat (browbeat, browbeaten/browbeat)", "Запугивать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "build (built, built)", "Строить", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "burn (burned/burnt, burned/burnt)", "Гореть, жечь", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "burst (burst, burst)", "Взрываться, прорываться", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "bust (busted/bust, busted/bust)", "Разжаловать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "buy (bought, bought)", "Покупать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "can (could, could)", "Мочь, уметь", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "cast (cast, cast)", "Бросить, кинуть, вышвырнуть", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "catch (caught, caught)", "Ловить, хватать, успеть", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "choose (chose, chosen)", "Выбирать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "cling (clung, clung)", "Цепляться, льнуть", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "clothe (clothed/clad, clothed/clad", "Одевать (кого-либо)", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "come (came, come)", "Приходить", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "cost (cost, cost)", "Стоить, обходиться (в какую-либо сумму)", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "creep (crept, crept)", "Ползать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "cut (cut, cut)", "Резать, разрезать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "deal (dealt, dealt)", "Иметь дело", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "dig (dug, dug)", "Копать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "dive (dove/dived, dived)", "Нырять, погружаться", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "do (did, done)", "Делать, выполнять", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "draw (drew, drawn)", "Рисовать, чертить", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "dream (dreamed/dreamt, dreamed/dreamt)", "Грезить, мечтать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "drink (drank, drunk)", "Пить", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "drive (drove, driven)", "Управлять (авто)", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "dwell (dwelt/dwelled, dwelt/dwelled)", "Обитать, находиться", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "eat (ate, eaten)", "Есть, кушать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "fall (fell, fallen)", "Падать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "feed (fed, fed)", "Кормить", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "feel (felt, felt)", "Чувствовать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "fight (fought, fought)", "Драться, сражаться, бороться", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "find (found, found)", "Находить", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "fit (fit, fit)", "Подходить по размеру", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "flee (fled, fled)", "Убегать, спасаться", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "fling (flung, flung)", "Бросаться, ринуться", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "fly (flew, flown)", "Летать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "forbid (forbade, forbidden)", "Запрещать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "forecast (forecast, forecast)", "Предсказывать, предвосхищать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "foresee (foresaw, foreseen)", "Предвидеть", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "foretell (foretold, foretold)", "Предсказывать, прогнозировать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "forget (forgot, forgotten)", "Забывать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "forgive (forgave, forgiven)", "Прощать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "forsake (forsook, forsaken)", "Покидать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "freeze (froze, frozen)", "Замерзать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "get (got, gotten/got)", "Получать, достигать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "give (gave, given)", "Давать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "go (went, gone)", "Идти, ехать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "grind (ground, ground)", "Молоть, толочь", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "grow (grew, grown)", "Расти", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "hang (hung/hanged, hung/hanged)", "Вешать, развешивать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "have has (had, had)", "Иметь", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "hear (heard, heard)", "Слышать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "hew (hewed, hewn/hewed)", "Рубить", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "hide (hid, hidden)", "Прятаться, скрываться", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "hit (hit, hit)", "Ударять, поражать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "hold (held, held)", "Держать, удерживать, фиксировать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "hurt (hurt, hurt)", "Ранить, причинить боль", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "inlay (inlaid, inlaid)", "Вкладывать, вставлять, выстилать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "input (input/inputted, input/inputted)", "Входить", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "interweave (interwove, interwoven)", "Воткать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "keep (kept, kept)", "Держать, хранить", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "kneel (knelt/kneeled, knelt/kneeled)", "Становиться на колени", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "knit (knitted/knit, knitted/knit)", "Вязать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "know (knew, known)", "Знать, иметь представление (о чем-либо)", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "lay (laid, laid)", "Класть, положить", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "lead (led, led)", "Вести, руководить, управлять", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "lean (leaned/leant, leaned/leant)", "Опираться, прислоняться", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "leap (leaped/leapt, leaped/leapt)", "Прыгать, скакать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "learn (learnt/learned, learnt/learned)", "Учить", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "leave (left, left)", "Покидать, оставлять", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "lend (lent, lent)", "Одалживать, давать взаймы", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "let (let, let)", "Позволять, предполагать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "lie (lay, lain)", "Лежать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "light (lit/lighted, lit/lighted)", "Освещать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "lose (lost, lost)", "Терять", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "make (made, made)", "Делать, производить, создавать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "may (might, might)", "Мочь, иметь возможность", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "mean (meant, meant)", "Значить, иметь ввиду", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "meet (met, met)", "Встречать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "mow (mowed, mowed/mown)", "Косить", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "offset (offset, offset)", "Возмещать, вознаграждать, компенсировать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "outbid (outbid, outbid)", "Перебивать цену", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "outdo (outdid, outdone)", "Превосходить", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "outfight (outfought, outfought)", "Побеждать в бою", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "outgrow (outgrew, outgrown)", "Вырастать из", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "output (output/outputted, output/outputted)", "Выходить", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "outrun (outran, outrun)", "Перегонять, опережать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "outsell (outsold, outsold)", "Продавать лучше или дороже", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "outshine (outshone, outshone)", "Затмевать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "overbid (overbid, overbid)", "Повелевать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "overcome (overcame, overcome)", "Компенсировать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "overdo (overdid, overdone)", "Пережари(ва)ть", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "overdraw (overdrew, overdrawn)", "Превышать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "overeat (overate, overeaten)", "Объедаться", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "overfly (overflew, overflown)", "Перелетать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "overhang (overhung, overhung)", "Нависать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "overhear (overheard, overheard)", "Подслуш(ив)ать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "overlay (overlaid, overlaid)", "Покры(ва)ть", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "overpay (overpaid, overpaid)", "Переплачивать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "override (overrode, overridden)", "Отменять, аннулировать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "overrun (overran, overrun)", "Переливаться через край", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "oversee (oversaw, overseen)", "Надзирать за", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "overshoot (overshot, overshot)", "Расстрелять", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "oversleep (overslept, overslept)", "Проспать, заспаться", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "overtake (overtook, overtaken)", "Догонять", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "overthrow (overthrew, overthrown)", "Свергать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "partake (partook, partaken)", "Принимать участие", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "pay (paid, paid)", "Платить", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "plead( pleaded/pled, pleaded/pled)", "Обращаться к суду", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "prepay (prepaid, prepaid)", "Платить вперед", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "prove (proved, proven/proved)", "Доказывать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "put (put, put)", "Класть, ставить, размещать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "quit (quit/quitted, quit/quitted)", "Выходить, покидать, оставлять", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "read (read, read)", "Читать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "rid (rid, rid)", "Избавлять", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "ride (rode, ridden)", "Ездить верхом", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "ring (rang, rung)", "Звонить", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "rise (rose, risen)", "Подняться", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "run (ran, run)", "Бегать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "saw (sawed, sawed/sawn)", "Пилить", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "say (said, said)", "Сказать, заявить", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "see (saw, seen)", "Видеть", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "seek (sought, sought)", "Искать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "sell (sold, sold)", "Продавать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "send (sent, sent)", "Посылать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "set (set, set)", "Ставить устанавливать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "sew (sewed, sewn/sewed)", "Шить", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "shake (shook, shaken)", "Трясти", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "shave (shaved, shaved/shaven)", "Бриться", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "shear (sheared, sheared/shorn)", "Стричь", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "shed (shed, shed)", "Проливать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "shine (shined/shone, shined/shone)", "Светить, сиять, озарять", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "shoot (shot, shot)", "Стрелять, давать побеги", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "show (showed, shown/showed)", "Показывать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "shrink (shrank/shrunk, shrunk)", "Сокращаться, сжиматься", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "shut (shut, shut)", "Закрывать, запирать, затворять", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "sing (sang, sung)", "Петь", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "sink (sank/sunk, sunk)", "Тонуть, погружаться (под воду)", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "sit (sat, sat)", "Сидеть", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "slay (slew/slayed, slain/slayed)", "Убивать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "sleep (slept, slept)", "Спать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "slide (slid, slid)", "Скользить", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "sling (slung, slung)", "Бросать, швырять", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "slink (slunk, slunk)", "Красться, идти крадучись", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "slit (slit, slit)", "Разрезать, рвать в длину", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "smell (smelled/smelt, smelled/smelt)", "Пахнуть, нюхать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "sow (sowed, sown/sowed)", "Сеять", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "speak (spoke, spoken)", "Говорить", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "speed (sped/speeded, sped/speeded)", "Ускорять, спешить", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "spell (spelled/spelt, spelled/spelt)", "Писать или читать по буквам", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "spend (spent, spent)", "Тратить, расходовать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "spill (spilled/spilt, spilled / spilt)", "Проливать, разливать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "spin (spun, spun)", "Прясть", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "spit (spit/spat, spit/spat)", "Плевать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "split (split, split)", "Расщеплять", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "spoil (spoiled/spoilt, spoiled/spoilt)", "Портить", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "spread (spread, spread)", "Распространиться", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "spring (sprang/sprung, sprung)", "Вскочить, возникнуть", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "stand (stood, stood)", "Стоять", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "steal (stole, stolen)", "Воровать, красть", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "stick (stuck, stuck)", "Уколоть, приклеить", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "sting (stung, stung)", "Жалить", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "stink (stunk/stank, stunk)", "Вонять", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "strew (strewed, strewn/strewed)", "Усеять, устлать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "stride (strode, stridden)", "Шагать, наносить удар", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "strike (struck, struck)", "Ударить, бить, бастовать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "string (strung, strung)", "Нанизать, натянуть", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "strive (strove/strived, striven/strived)", "Стараться", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "sublet (sublet, sublet)", "Передавать в субаренду", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "swear (swore, sworn)", "Клясться, присягать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "sweep (swept, swept)", "Мести, подметать, сметать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "swell (swelled, swollen/swelled)", "Разбухать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "swim (swam, swum)", "Плавать, плыть", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "swing (swung, swung)", "Качать, раскачивать, вертеть", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "take (took, taken)", "Брать, взять", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "teach (taught, taught)", "Учить, обучать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "tear (tore, torn)", "Рвать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "tell (told, told)", "Рассказать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "think (thought, thought)", "Думать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "throw (threw, thrown)", "Бросить", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "thrust (thrust, thrust)", "Колоть, пронзать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "tread (trod, trodden/trod)", "Ступать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "unbend (unbent, unbent)", "Выпрямляться, разгибаться", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "underbid (underbid, underbid)", "Снижать цену", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "undercut (undercut, undercut)", "Сбивать цены", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "undergo (underwent, undergone)", "Испытывать, переносить", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "underlie (underlay, underlain)", "Лежать в основе", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "underpay (underpaid, underpaid)", "Оплачивать слишком низко", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "undersell (undersold, undersold)", "Продавать дешевле", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "understand (understood, understood)", "Понимать, постигать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "undertake (undertook, undertaken)", "Предпринять", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "underwrite (underwrote, underwritten)", "Подписываться", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "undo (undid, undone)", "Уничтожать сделанное", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "unfreeze (unfroze, unfrozen)", "Размораживать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "unsay (unsaid, unsaid)", "Брать назад свои слова", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "unwind (unwound, unwound)", "Развертывать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "uphold (upheld, upheld)", "Поддерживать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "upset (upset, upset)", "Опрокинуться", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "wake (woke/waked, woken/waked)", "Просыпаться", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "waylay (waylaid, waylaid)", "Подстерегать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "wear (wore, worn)", "Носить (одежду)", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "weave (wove/weaved, woven/weaved)", "Ткать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "wed (wed/wedded, wed/wedded)", "Жениться, выдавать замуж", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "weep (wept, wept)", "Плакать, рыдать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "wet (wet/wetted, wet/wetted)", "Мочить, увлажнять", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "win (won, won)", "Победить, выиграть", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "wind (wound, wound)", "Заводить (механизм)", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "withdraw (withdrew, withdrawn)", "Взять назад, отозвать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "withhold (withheld, withheld)", "Воздерживаться, отказывать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "withstand (withstood, withstood)", "Противостоять", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "wring (wrung, wrung)", "Скрутить, сжимать", "Неправильные глаголы"))
//                addGeneralWord(Word(0, "write (wrote, written)", "Писать", "Неправильные глаголы"))
//            }
//            with(addGeneralWordUseCase){
//                addGeneralWord(Word(0, "adapt", "Настраивать", "IT-термины"))
//                addGeneralWord(Word(0, "address book", "Адресная книга", "IT-термины"))
//                addGeneralWord(Word(0, "add to list", "Добавлять в список", "IT-термины"))
//                addGeneralWord(Word(0, "application", "Приложение", "IT-термины"))
//                addGeneralWord(Word(0, "archive", "Архивировать", "IT-термины"))
//                addGeneralWord(Word(0, "attempt", "Попытка", "IT-термины"))
//                addGeneralWord(Word(0, "authorization", "Авторизация", "IT-термины"))
//                addGeneralWord(Word(0, "automatically", "Автоматически", "IT-термины"))
//                addGeneralWord(Word(0, "available format", "Доступный формат", "IT-термины"))
//                addGeneralWord(Word(0, "backup", "Резервная копия", "IT-термины"))
//                addGeneralWord(Word(0, "binary", "Двоичный", "IT-термины"))
//                addGeneralWord(Word(0, "blowfish", "Блоуфиш (криптографический алгоритм)", "IT-термины"))
//                addGeneralWord(Word(0, "buffer", "Буфер", "IT-термины"))
//                addGeneralWord(Word(0, "cache", "Кэш", "IT-термины"))
//                addGeneralWord(Word(0, "cancel", "Отменить", "IT-термины"))
//                addGeneralWord(Word(0, "capacity", "Емкость", "IT-термины"))
//                addGeneralWord(Word(0, "case-sensitive", "С учетом регистра клавиатуры", "IT-термины"))
//                addGeneralWord(Word(0, "catalog", "Каталог", "IT-термины"))
//                addGeneralWord(Word(0, "change directory", "Изменить каталог", "IT-термины"))
//                addGeneralWord(Word(0, "command line", "Командная строка", "IT-термины"))
//                addGeneralWord(Word(0, "compatible", "Совместимый", "IT-термины"))
//                addGeneralWord(Word(0, "component", "Компонент", "IT-термины"))
//                addGeneralWord(Word(0, "confidential", "Конфиденциальный", "IT-термины"))
//                addGeneralWord(Word(0, "configuration", "Конфигурация", "IT-термины"))
//                addGeneralWord(Word(0, "connection", "Соединение", "IT-термины"))
//                addGeneralWord(Word(0, "cookie", "Файлы данных типа cookie", "IT-термины"))
//                addGeneralWord(Word(0, "create", "Создавать", "IT-термины"))
//                addGeneralWord(Word(0, "database administration", "Администратор базы данных", "IT-термины"))
//                addGeneralWord(Word(0, "data source", "Источник данных", "IT-термины"))
//                addGeneralWord(Word(0, "data storage", "Накопление данных", "IT-термины"))
//                addGeneralWord(Word(0, "data transfer", "Передача данных", "IT-термины"))
//                addGeneralWord(Word(0, "debug", "Отлаживать", "IT-термины"))
//                addGeneralWord(Word(0, "default", "По умолчанию", "IT-термины"))
//                addGeneralWord(Word(0, "developer", "Разработчик", "IT-термины"))
//                addGeneralWord(Word(0, "device", "Устройство", "IT-термины"))
//                addGeneralWord(Word(0, "digital", "Цифровой", "IT-термины"))
//                addGeneralWord(Word(0, "display", "Дисплей", "IT-термины"))
//                addGeneralWord(Word(0, "double-click", "Двойной щелчок мышью", "IT-термины"))
//                addGeneralWord(Word(0, "download", "Загружать", "IT-термины"))
//                addGeneralWord(Word(0, "edit", "Редактировать", "IT-термины"))
//                addGeneralWord(Word(0, "electronic", "Электронный", "IT-термины"))
//                addGeneralWord(Word(0, "embed", "Встраивать", "IT-термины"))
//                addGeneralWord(Word(0, "encrypt", "Шифровать", "IT-термины"))
//                addGeneralWord(Word(0, "ensure", "Обеспечивать", "IT-термины"))
//                addGeneralWord(Word(0, "enter", "Ввод", "IT-термины"))
//                addGeneralWord(Word(0, "error", "Ошибка", "IT-термины"))
//                addGeneralWord(Word(0, "file name", "Имя файла", "IT-термины"))
//                addGeneralWord(Word(0, "firewall", "брандмауэр", "IT-термины"))
//                addGeneralWord(Word(0, "function", "Функция", "IT-термины"))
//                addGeneralWord(Word(0, "give feedback", "Осуществлять обратную связь", "IT-термины"))
//                addGeneralWord(Word(0, "hardware", "Оборудование", "IT-термины"))
//                addGeneralWord(Word(0, "import", "Импортировать", "IT-термины"))
//                addGeneralWord(Word(0, "initial size", "Исходный размер", "IT-термины"))
//                addGeneralWord(Word(0, "install", "Устанавливать", "IT-термины"))
//                addGeneralWord(Word(0, "interchange", "Обмен", "IT-термины"))
//                addGeneralWord(Word(0, "interface", "Интерфейс", "IT-термины"))
//                addGeneralWord(Word(0, "justify", "Выравнивать", "IT-термины"))
//                addGeneralWord(Word(0, "knowledge", "Сведения", "IT-термины"))
//                addGeneralWord(Word(0, "last modified", "Последний раз изменено", "IT-термины"))
//                addGeneralWord(Word(0, "mark as read", "Отметить как прочитанное", "IT-термины"))
//                addGeneralWord(Word(0, "multifunctional", "Многофункциональный", "IT-термины"))
//                addGeneralWord(Word(0, "operation system", "Операционная система", "IT-термины"))
//                addGeneralWord(Word(0, "playback", "Воспроизведение", "IT-термины"))
//                addGeneralWord(Word(0, "pop-up menu", "Всплывающее меню", "IT-термины"))
//                addGeneralWord(Word(0, "power", "Мощность", "IT-термины"))
//                addGeneralWord(Word(0, "prerelease", "Предварительный выпуск", "IT-термины"))
//                addGeneralWord(Word(0, "press", "Нажимать", "IT-термины"))
//                addGeneralWord(Word(0, "programming language", "Язык программирования", "IT-термины"))
//                addGeneralWord(Word(0, "property", "Свойство", "IT-термины"))
//                addGeneralWord(Word(0, "protect", "Защищать", "IT-термины"))
//                addGeneralWord(Word(0, "protocol", "Протокол", "IT-термины"))
//                addGeneralWord(Word(0, "read only", "Предназначенный только для чтения", "IT-термины"))
//                addGeneralWord(Word(0, "registered", "Зарегистрированный", "IT-термины"))
//                addGeneralWord(Word(0, "remote administration", "Удаленное администрирование", "IT-термины"))
//                addGeneralWord(Word(0, "sample", "Образец", "IT-термины"))
//                addGeneralWord(Word(0, "scale", "Масштаб, шкала", "IT-термины"))
//                addGeneralWord(Word(0, "scroll bar", "Полоса прокрутки", "IT-термины"))
//                addGeneralWord(Word(0, "server", "Сервер", "IT-термины"))
//                addGeneralWord(Word(0, "share", "Совместно использовать", "IT-термины"))
//                addGeneralWord(Word(0, "software", "Программное обеспечение", "IT-термины"))
//                addGeneralWord(Word(0, "support", "Поддержка", "IT-термины"))
//                addGeneralWord(Word(0, "system administrator", "Системный администратор", "IT-термины"))
//                addGeneralWord(Word(0, "system manager", "Системный менеджер", "IT-термины"))
//                addGeneralWord(Word(0, "taskbar", "Панель задач", "IT-термины"))
//                addGeneralWord(Word(0, "technical support", "Техническая поддержка", "IT-термины"))
//                addGeneralWord(Word(0, "technology", "Технология", "IT-термины"))
//                addGeneralWord(Word(0, "toolbar", "Панель инструментов", "IT-термины"))
//                addGeneralWord(Word(0, "transmit", "Передавать", "IT-термины"))
//                addGeneralWord(Word(0, "underline", "Подчеркивать", "IT-термины"))
//                addGeneralWord(Word(0, "unexpected", "Неожиданный", "IT-термины"))
//                addGeneralWord(Word(0, "update", "Обновлять", "IT-термины"))
//                addGeneralWord(Word(0, "usability", "Доступность для использования", "IT-термины"))
//                addGeneralWord(Word(0, "user name", "Имя пользователя", "IT-термины"))
//                addGeneralWord(Word(0, "verify", "Проверить", "IT-термины"))
//                addGeneralWord(Word(0, "virtual memory", "Виртуальная память", "IT-термины"))
//                addGeneralWord(Word(0, "warehouse", "Хранилище", "IT-термины"))
//                addGeneralWord(Word(0, "web hosting", "Хостинг", "IT-термины"))
//                addGeneralWord(Word(0, "zero out", "Обнулять", "IT-термины"))
//                addGeneralWord(Word(0, "zoom", "Масштаб", "IT-термины"))
//                addGeneralWord(Word(0, "zoom in", "Увеличить масштаб", "IT-термины"))
//                addGeneralWord(Word(0, "zoom out", "Уменьшить масштаб", "IT-термины"))
//            }

//
        }
    }


}